-- 1. Create Tables (Using IF NOT EXISTS)
CREATE TABLE IF NOT EXISTS public.achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    class_name TEXT,
    achievement TEXT NOT NULL,
    level TEXT NOT NULL,
    year TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('akademik', 'non-akademik')),
    type TEXT NOT NULL CHECK (type IN ('student', 'teacher')),
    image TEXT
);

CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    file_url TEXT NOT NULL,
    file_size TEXT NOT NULL,
    file_type TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    full_name TEXT NOT NULL,
    nisn TEXT UNIQUE,
    class_name TEXT,
    gender TEXT,
    birth_place TEXT,
    birth_date DATE,
    address TEXT,
    parent_name TEXT,
    phone TEXT
);

CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_name TEXT NOT NULL,
    action TEXT NOT NULL,
    description TEXT,
    target TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.teachers_staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    full_name TEXT NOT NULL,
    nip TEXT,
    position TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('guru', 'staf')),
    photo_url TEXT,
    subject TEXT
);

CREATE TABLE IF NOT EXISTS public.org_structure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    hierarchy_order INTEGER DEFAULT 0,
    photo_url TEXT
);

CREATE TABLE IF NOT EXISTS public.academic_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    type TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    last_updated_by TEXT
);

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE,
    username TEXT UNIQUE,
    full_name TEXT,
    role TEXT DEFAULT 'student' CHECK (role IN ('admin', 'operator', 'student')),
    email TEXT,
    phone TEXT,
    address TEXT,
    avatar_url TEXT
);

-- 2. Enable RLS
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teachers_staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.org_structure ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.academic_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 3. Create/Replace Policies
-- Profiles
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
DROP POLICY IF EXISTS "Admin can view all profiles" ON public.profiles;
CREATE POLICY "Admin can view all profiles" ON public.profiles FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Achievements
DROP POLICY IF EXISTS "Allow public read access to achievements" ON public.achievements;
CREATE POLICY "Allow public read access to achievements" ON public.achievements FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow authenticated users full access to achievements" ON public.achievements;
CREATE POLICY "Allow authenticated users full access to achievements" ON public.achievements FOR ALL USING (auth.role() = 'authenticated');

-- Messages
DROP POLICY IF EXISTS "Allow public to insert messages" ON public.messages;
CREATE POLICY "Allow public to insert messages" ON public.messages FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow authenticated users to view/delete messages" ON public.messages;
CREATE POLICY "Allow authenticated users to view/delete messages" ON public.messages FOR ALL USING (auth.role() = 'authenticated');

-- Documents
DROP POLICY IF EXISTS "Allow public read access to documents" ON public.documents;
CREATE POLICY "Allow public read access to documents" ON public.documents FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow authenticated users full access to documents" ON public.documents;
CREATE POLICY "Allow authenticated users full access to documents" ON public.documents FOR ALL USING (auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    image TEXT NOT NULL
);

ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to gallery" ON public.gallery;
CREATE POLICY "Allow public read access to gallery" ON public.gallery FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow authenticated users full access to gallery" ON public.gallery;
CREATE POLICY "Allow authenticated users full access to gallery" ON public.gallery FOR ALL USING (auth.role() = 'authenticated');

-- Students
DROP POLICY IF EXISTS "Only authenticated users can view/manage students" ON public.students;
CREATE POLICY "Only authenticated users can view/manage students" ON public.students FOR ALL USING (auth.role() = 'authenticated');

-- Activity Logs
DROP POLICY IF EXISTS "Only authenticated users can view/manage activity_logs" ON public.activity_logs;
CREATE POLICY "Only authenticated users can view/manage activity_logs" ON public.activity_logs FOR ALL USING (auth.role() = 'authenticated');

-- Teachers/Staff
DROP POLICY IF EXISTS "Allow public read access to teachers_staff" ON public.teachers_staff;
CREATE POLICY "Allow public read access to teachers_staff" ON public.teachers_staff FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow authenticated users full access to teachers_staff" ON public.teachers_staff;
CREATE POLICY "Allow authenticated users full access to teachers_staff" ON public.teachers_staff FOR ALL USING (auth.role() = 'authenticated');

-- Org Structure
DROP POLICY IF EXISTS "Allow public read access to org_structure" ON public.org_structure;
CREATE POLICY "Allow public read access to org_structure" ON public.org_structure FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow authenticated users full access to org_structure" ON public.org_structure;
CREATE POLICY "Allow authenticated users full access to org_structure" ON public.org_structure FOR ALL USING (auth.role() = 'authenticated');

-- Academic Sections
DROP POLICY IF EXISTS "Allow public read access to academic_sections" ON public.academic_sections;
CREATE POLICY "Allow public read access to academic_sections" ON public.academic_sections FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow authenticated users full access to academic_sections" ON public.academic_sections;
CREATE POLICY "Allow authenticated users full access to academic_sections" ON public.academic_sections FOR ALL USING (auth.role() = 'authenticated');

-- 4. Storage Policies (Run once after creating 'files' bucket)
/*
  DROP POLICY IF EXISTS "Public Read Access" ON storage.objects;
  CREATE POLICY "Public Read Access" ON storage.objects FOR SELECT USING (bucket_id = 'files');
  DROP POLICY IF EXISTS "Authenticated Upload" ON storage.objects;
  CREATE POLICY "Authenticated Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'files' AND auth.role() = 'authenticated');
  DROP POLICY IF EXISTS "Authenticated Update" ON storage.objects;
  CREATE POLICY "Authenticated Update" ON storage.objects FOR UPDATE USING (bucket_id = 'files' AND auth.role() = 'authenticated');
  DROP POLICY IF EXISTS "Authenticated Delete" ON storage.objects;
  CREATE POLICY "Authenticated Delete" ON storage.objects FOR DELETE USING (bucket_id = 'files' AND auth.role() = 'authenticated');
*/

-- 5. Trigger for New User Profile
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name, role, email)
  VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data->>'full_name', 'student', NEW.email);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- SPMB Tables
CREATE TABLE IF NOT EXISTS public.spmb_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    gender TEXT,
    birth_date TEXT,
    address TEXT,
    previous_school TEXT,
    parents_name TEXT,
    parents_phone TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    submitted_date TEXT
);

CREATE TABLE IF NOT EXISTS public.spmb_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    event_name TEXT NOT NULL,
    date_range TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.spmb_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    description TEXT NOT NULL
);

-- Enable RLS for SPMB
ALTER TABLE public.spmb_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spmb_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spmb_requirements ENABLE ROW LEVEL SECURITY;

-- Policies for SPMB Applications
DROP POLICY IF EXISTS "Public can insert applications" ON public.spmb_applications;
CREATE POLICY "Public can insert applications" ON public.spmb_applications FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Authenticated users full access applications" ON public.spmb_applications;
CREATE POLICY "Authenticated users full access applications" ON public.spmb_applications FOR ALL USING (auth.role() = 'authenticated');

-- Policies for SPMB Schedule
DROP POLICY IF EXISTS "Public read access schedule" ON public.spmb_schedule;
CREATE POLICY "Public read access schedule" ON public.spmb_schedule FOR SELECT USING (true);
DROP POLICY IF EXISTS "Authenticated users full access schedule" ON public.spmb_schedule;
CREATE POLICY "Authenticated users full access schedule" ON public.spmb_schedule FOR ALL USING (auth.role() = 'authenticated');

-- Policies for SPMB Requirements
DROP POLICY IF EXISTS "Public read access requirements" ON public.spmb_requirements;
CREATE POLICY "Public read access requirements" ON public.spmb_requirements FOR SELECT USING (true);
DROP POLICY IF EXISTS "Authenticated users full access requirements" ON public.spmb_requirements;
CREATE POLICY "Authenticated users full access requirements" ON public.spmb_requirements FOR ALL USING (auth.role() = 'authenticated');
